### ISSUE TITLE
Put a warning for developers when changing the flutter branches to master [Enhancement]

### ISSUE THREAD

**Issue by 3mrdev** [hmziqrs/flutter-ui-designs#9]
Great and awesome repo keep up the good work.

I just wanted to say that changing from flutter stable to flutter master channel will result in discarding the previous flutter sdk and dart sdk. 

So a better approach is to copy and paste your current flutter sdk in a new folder and rename it flutter_master and then continue with next steps so you don't lose your stable flutter sdk 

or use this dart cli to manage more than on flutter sdk by command line interface called [fvm](https://github.com/leoafarias/fvm)

A warning in the readme file will do the job . Thanks in advance @hackerhgl

**Comment by hmziqrs** [comment]
You're definitely right I didn't think about the core sdk change as I always use master branch for development. I'll look into the **FVM** approach It'll be really good users don't lost their stable just to run the repo.

Thank your for your time to write the review I'll definitely look into this as soon as I get free from current project.

**Comment by 3mrdev** [comment]
@hackerhgl You are very welcome .. Happy to help.
